# Generated by Django 4.2.2 on 2023-06-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsistemsolar',
            name='answer',
            field=models.CharField(max_length=50),
        ),
    ]
