# Generated by Django 4.2.2 on 2023-06-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_testsistemsolar_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSistemSolar',
        ),
    ]
