# Generated by Django 4.2.2 on 2023-06-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_testsistemsolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSistemSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
